name: Deploy Tienda de Perritos

on:
  push:
    branches: [ "deploy" ] # Se activa solo cuando subes cambios a la rama deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Desplegar en EC2 vía SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Entrar a la carpeta del proyecto o crearla si no existe
            mkdir -p ~/tienda-perritos_EC2
            cd ~/tienda-perritos_EC2
            
            # Comandos para limpiar y levantar los contenedores
            # Nota: Asegúrate de que docker-compose esté instalado en tu EC2
            sudo docker-compose down || true
            sudo docker-compose up -d --build.