name: Deploy Tienda de Perritos

on:
  push:
    branches: [ "deploy" ] # Se activa solo cuando subes cambios a la rama deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Desplegar en EC2 con Debug Pro
        run: |
          # 1. Crear el archivo de la llave con el secreto
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          
          # 2. Intentar conexión con SSH Verbose (-vvv) para ver el error real
          ssh -o StrictHostKeyChecking=no -v -i private_key.pem ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            echo "Conexión exitosa al servidor!"
            mkdir -p ~/tienda-perritos_EC2
            cd ~/tienda-perritos_EC2
            sudo docker-compose down || true
            sudo docker-compose up -d --build
          EOF