name: Deploy Tienda de Perritos

on:
  push:
    branches: [ "deploy" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Transferir archivos y Desplegar
        run: |
          # 1. Preparar la llave
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          
          # 2. Crear la carpeta en la EC2 (por si acaso)
          ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@${{ secrets.EC2_HOST }} "mkdir -p ~/tienda-perritos_EC2"
          
          # 3. COPIAR LOS ARCHIVOS (La pieza que faltaba)
          # Copiamos todo el contenido actual a la carpeta de la EC2
          scp -o StrictHostKeyChecking=no -i private_key.pem -r ./* ec2-user@${{ secrets.EC2_HOST }}:~/tienda-perritos_EC2
          
          # 4. EJECUTAR DOCKER EN EL SERVIDOR
          ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/tienda-perritos_EC2
            sudo docker-compose down || true
            sudo docker-compose up -d --build
            echo "Despliegue completado con éxito."
          EOF